name: neekle
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.3
  cloud_functions: ^4.1.1

  # State management
  flutter_bloc: ^8.1.2

  # DI
  get_it: ^7.3.0
  injectable: ^2.1.1

  # Route
  auto_route: ^7.2.0

  # Web3
  web3dart: ^2.6.1
  walletconnect_dart: ^0.0.11

  # DB
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Extensions
  rxdart: ^0.27.7
  http: ^0.13.6
  google_fonts: ^4.0.4
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.5
  qr_flutter: ^4.0.0
  extended_image: ^8.0.1
  flutter_rating_bar: ^4.0.1
  flutter_tags: 1.0.0-nullsafety.1
  infinite_scroll_pagination: ^3.2.0
  sliver_tools: ^0.2.10
  web_socket_channel: ^2.4.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  auto_route_generator: ^7.1.1
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  isar_generator: 3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/strings/
